# -*- coding: utf-8 -*-
"""GráficoTyA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dBKYwHmd7xEnzWoCsO0piUwHT14ZRs9K
"""

#importing pandas profiling library
!pip install ydata-profiling

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
from ydata_profiling import ProfileReport
import matplotlib.cm as cm
#from google.colab import drive
#drive.mount('/content/drive')

"""##Descargamos las Bases de Datos

Quitamos Método de Hidratación de Mixteca Oaxaqueña, para después evaluarla individualmente.

También descartamos Chiapas Molienda Grande, debido a que se observen mejor las gráficas.
"""

# Absorción
file_suffix_A=['AChMN','AGoMG','AMiMG','AOxMM','AIlly']

for file_name in file_suffix_A:

  file_path=f'/content/drive/MyDrive/CafeLab/Data /{file_name}.txt'
  file=pd.read_csv(file_path,engine='python',sep='\t',skiprows=8)
  file.iloc[:,1]=pd.to_numeric(file['A'],errors='coerce')
  file=pd.DataFrame(file)

  globals()[file_name] = file
  print(file_name+'     CARGADO')


  for porce in {'05','20','50'}:
    try:
      file_path=f'/content/drive/MyDrive/CafeLab/Data /{file_name}{porce}.txt'
      file=pd.read_csv(file_path,engine='python',sep='\t',skiprows=8)
      file.iloc[:,1]=pd.to_numeric(file['A'],errors='coerce')
      file=pd.DataFrame(file)

      globals()[file_name+porce] = file
      print(file_name+porce+'     CARGADO')

    except FileNotFoundError:
      print(f"No se encontró el archivo {file_name+porce}.txt")

# Transmitancia
file_suffix_T= ['TChMN','TGoMG','TMiMG','TOxMM','TIlly']

for file_name in file_suffix_T:

  file_path=f'/content/drive/MyDrive/CafeLab/Data /{file_name}.txt'
  file=pd.read_csv(file_path,engine='python',sep='\t',skiprows=8)
  file.iloc[:,1]=pd.to_numeric(file['%T'],errors='coerce')
  file=pd.DataFrame(file)

  globals()[file_name] = file
  print(file_name+'     CARGADO')


  for porce in {'05','20','50'}:
    try:
      file_path=f'/content/drive/MyDrive/CafeLab/Data /{file_name}{porce}.txt'
      file=pd.read_csv(file_path,engine='python',sep='\t',skiprows=8)
      file.iloc[:,1]=pd.to_numeric(file['%T'],errors='coerce')
      file=pd.DataFrame(file)

      globals()[file_name+porce] = file
      print(file_name+porce+'     CARGADO')

    except FileNotFoundError:
      print(f"No se encontró el archivo {file_name+porce}.txt")

"""##Gráficas

### Gráfica de Absorción y Transmitancia de:
- ILLY  MM
- CHIAPAS MN
- MIXTECA OAXAQUEÑA MG
- OAXACA MM
- GUERRERO MG
"""

# Asegúrate de que file_suffix_A y file_suffix_T sean listas
file_suffix_A = list(file_suffix_A)
file_suffix_T = list(file_suffix_T)

fig = plt.figure(figsize=(20,20))
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)

cmap_A = cm.get_cmap('tab10', len(file_suffix_A))  # cambia a 'tab20' si necesitas más colores
cmap_T = cm.get_cmap('Set1', len(file_suffix_T))

# Graficar absorbancia con colores variables (azul -> violeta)
for i, name in enumerate(file_suffix_A):
    df = globals()[name]
    color = cmap_A(i)  # genera un color azul-violeta distinto
    ax1.plot(df['nm'], df['A'], color=color, label=name)

ax1.set_title("Absorbancia", fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right')

# Graficar transmitancia con colores variables (rojo -> naranja claro)
for i, name in enumerate(file_suffix_T):
    df = globals()[name]
    color = cmap_T(i)  # genera un color rojo-anaranjado distinto
    ax2.plot(df['nm'], df['%T'], color=color, label=name)

ax2.set_title("Transmitancia", fontsize=20)
ax2.set_xlabel('Longitud de Onda (nm)')
ax2.set_ylabel('Transmitancia (%)')
ax2.legend(loc='upper left')

fig.tight_layout()
plt.show()

"""### Gráficas de Absorción
- ILLY - CHIAPAS
- ILLY - GUERRERO
- ILLY - MIXTECA OAXAQUEÑA
- ILLY - OAXACA
"""

# Asegúrate de que file_suffix_A y file_suffix_T sean listas
file_suffix_A = [x for x in file_suffix_A if x != 'AIlly']

fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(20,20))
ax = ax.flatten()

cmap_A = cm.get_cmap('tab10', len(file_suffix_A))  # cambia a 'tab20' si necesitas más colores

# Graficar absorbancia con colores variables (azul -> violeta)
for i, name in enumerate(file_suffix_A):

    df = globals()[name]
    Illy = globals()['AIlly']
    color = cmap_A(i)  # genera un color azul-violeta distinto
    ax[i].plot(df['nm'], df['A'], color=color, label=name)
    ax[i].plot(Illy['nm'], Illy['A'], color='black', label='Illy')
    ax[i].set_title(f'AIlly vs {name}', fontsize=20)
    ax[i].set_xlabel('Longitud de Onda (nm)')
    ax[i].set_ylabel('Absorbancia')
    ax[i].legend(loc='upper right')

fig.tight_layout()
plt.show()

"""### Gráficas de Transmitancia
- ILLY - CHIAPAS
- ILLY - GUERRERO
- ILLY - MIXTECA OAXAQUEÑA
- ILLY - OAXACA
"""

# Asegúrate de que file_suffix_A y file_suffix_T sean listas
file_suffix_A = [x for x in file_suffix_A if x != 'AIlly']
file_suffix_T = [x for x in file_suffix_T if x != 'TIlly']

fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(20,20))
ax = ax.flatten()

cmap_T = cm.get_cmap('Set1', len(file_suffix_T))

# Graficar absorbancia con colores variables (azul -> violeta)
for i, name in enumerate(file_suffix_T):

    df = globals()[name]
    Illy = globals()['TIlly']
    color = cmap_T(i)  # genera un color azul-violeta distinto
    ax[i].plot(df['nm'], df['%T'], color=color, label=name)
    ax[i].plot(Illy['nm'], Illy['%T'], color='black', label='Illy')
    ax[i].set_title(f'TIlly vs {name}', fontsize=20)
    ax[i].set_xlabel('Longitud de Onda (nm)')
    ax[i].set_ylabel('Transmitancia')
    ax[i].legend(loc='upper left')


fig.tight_layout()
plt.show()

"""### Gráficas de Absorción
Diferentes diluciones ( 05%, 20% y 50% ) con respecto de 15g de café.
"""

fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(20,20))
ax = ax.flatten()

cmap_A = cm.get_cmap('tab20', len(file_suffix_A) * 3)  # 3 curvas por archivo

# Graficar absorbancia con colores variables (azul -> violeta)
for i, name in enumerate(file_suffix_A):
  Illy = globals()['AIlly']
  ax[i].plot(Illy['nm'], Illy['A'], color='black', label='Illy')

  for k, j in enumerate(['','05', '20', '50']):
      df = globals()[f'{name}{j}']
      color = cmap_A(i * 3 + k)  # cambia de color en cada combinación name+concentración

      #ax[i].plot(df['nm'], df['A'], color=color, label=f'{name}{j}')
      ax[i].plot(df['nm'], df['A'], color=color, label=f'{name}{j}')
      ax[i].set_title(f'AIlly vs {name}', fontsize=20)
      ax[i].set_xlabel('Longitud de Onda (nm)')
      ax[i].set_ylabel('Absorbancia')
      ax[i].legend(loc='upper right')

"""### Gráficas de Transmitancia
Diferentes diluciones ( 05%, 20% y 50% ) con respecto de 15g de café.
"""

fig, ax = plt.subplots(nrows=2, ncols=2, figsize=(20,20))
ax = ax.flatten()

cmap_T = cm.get_cmap('tab20', len(file_suffix_T) * 3)  # 3 curvas por archivo

# Graficar absorbancia con colores variables (azul -> violeta)
for i, name in enumerate(file_suffix_T):
  Illy = globals()['TIlly']
  ax[i].plot(Illy['nm'], Illy['%T'], color='black', label='Illy')

  for k, j in enumerate(['','05', '20', '50']):
      df = globals()[f'{name}{j}']
      color = cmap_T(i * 3 + k)  # cambia de color en cada combinación name+concentración

      ax[i].plot(df['nm'], df['%T'], color=color, label=f'{name}{j}')
      ax[i].set_title(f'TIlly vs {name}', fontsize=20)
      ax[i].set_xlabel('Longitud de Onda (nm)')
      ax[i].set_ylabel('Transmitancia')
      ax[i].legend(loc='upper left')











#---------------------------------------------------chiapas-----------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS
fig=plt.figure(figsize=(10,10))
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)


df = AChMG
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AChMG05['nm'],AChMG05['A'],color=(0.5,0.5,1),label='AChMG05')
ax1.plot(AChMG20['nm'],AChMG20[''],color=(0,0,1),label='AChMG20')
ax1.plot(AChMG50[:,0],AChMG50[:,1],color=(0,0,.7),label='AChMG50')

ax1.text(AChMG05[8,0], AChMG05[8,1],'204 nm', fontsize=8)
ax1.text(AChMG20[15,0], AChMG20[15,1],'207.5 nm', fontsize=8)
ax1.text(AChMG50[41,0], AChMG50[41,1],'220.5 nm', fontsize=8)

ax1.set_title("Absorbancia - Chiapas",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------
ax2.plot(TChMG05[:,0],TChMG05[:,1],color=(1,0.5,0.5),label='TChMG05')
ax2.plot(TChMG20[:,0],TChMG20[:,1],color=(1,0,0),label='TChMG20')
ax2.plot(TChMG50[:,0],TChMG50[:,1],color=(0.7,0,0),label='TChMG50')
ax2.set_title("Transmitancia - Chiapas",fontsize=20)
ax2.set_xlabel('Longitud de Onda (nm)')
ax2.set_ylabel('Transmitancia (%)')
ax2.legend(loc='upper left')

fig.tight_layout()

print(AChMN20['A'])

"""# Juntemos los datos en una misma y veamos las BANDAS"""

#CLEANING

ACh=pd.DataFrame({'nm':AChMN05['nm'],'A05':AChMN05['A'],'A20':AChMN20['A'],'A50':AChMN50['A']})
ACh.fillna(0,inplace=True)

TCh=pd.DataFrame({'nm':TChMG05['nm'],'T05':TChMG05['%T'],'T20':TChMG20['%T'],'T50':TChMG50['%T']})
TCh.fillna(0,inplace=True)
#-------------------------------------------------------------------------------------------------------

#ProfileReport(AChMG)

#AChMG['A05'].describe().loc[['min','max']]

#-------------------MINIMOS Y MAXIMOS-------------------------------------------
#print(AChMG[AChMG.iloc[:,1]==1.449])
#print(AChMG[AChMG.iloc[:,2]==1.528])
#print(AChMG[AChMG.iloc[:,3]==1.555])
print(ACh['A05'].describe().loc[['min','max']])
print(ACh['A20'].describe().loc[['min','max']])
print(ACh['A50'].describe().loc[['min','max']])

#GRAFICAMOS CON BANDAS
fig=plt.figure(figsize=(20,10))
ax1 = fig.add_subplot(1, 1, 1)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AChMG05['nm'],AChMG05['A'],color=(0.5,0.5,1),label='AChMG05')
ax1.plot(AChMG20['nm'],AChMG20['A'],color=(0,0,1),label='AChMG20')
ax1.plot(AChMG50['nm'],AChMG50['A'],color=(0,0,.7),label='AChMG50')

#ax1.axvline(x=AChMG_B1.iloc[43,0], color=(0.5,0.5,1), linestyle='--')
#ax1.axvline(x=AChMG_B1.iloc[46,0], color=(0,0,1), linestyle='--')
#ax1.axvline(x=AChMG_B1.iloc[47,0], color=(0,0,0.7), linestyle='--')

#ax1.axvline(x=AChMG_B2.iloc[11,0], color=(0.5,0.5,1), linestyle='--')
#ax1.axvline(x=AChMG_B2.iloc[16,0], color=(0,0,1), linestyle='--')
#ax1.axvline(x=AChMG_B2.iloc[12,0], color=(0,0,0.7), linestyle='--')

#ax1.text(268,0,'B1',color='k',fontsize=10)
#ax1.text(314,0,'B2',color='k',fontsize=10)

ax1.set_title("Absorbancia - Chiapas",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------

#Banda1  250 - 300
ACh_B1=ACh[(ACh['nm'] > 250) & (ACh['nm'] < 300)]
ACh_B1 = ACh_B1.reset_index()
ACh_B1.drop('index',axis=1,inplace=True)
ACh_B1.head()
#ProfileReport(ACh_B1)

#Banda1
print(ACh_B1[ACh_B1.iloc[:,1]==0.327])
print(ACh_B1[ACh_B1.iloc[:,2]==0.467])
print(ACh_B1[ACh_B1.iloc[:,3]==0.88])

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(ACh_B1.iloc[:,0],ACh_B1.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(ACh_B1.iloc[:,0],ACh_B1.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(ACh_B1.iloc[:,0],ACh_B1.iloc[:,3],color=(0,0,.7),label='A50')



#plt.axvline(x=ACh_B1.iloc[43,0], color=(0.5,0.5,1), linestyle='--')
#plt.axvline(x=ACh_B1.iloc[46,0], color=(0,0,1), linestyle='--')
#plt.axvline(x=ACh_B1.iloc[47,0], color=(0,0,0.7), linestyle='--')

#plt.text(ACh_B1.iloc[41,0],0.6,'272 nm - 0.327',rotation=90,color=(0.5,0.5,1),fontsize=8)
#plt.text(ACh_B1.iloc[44,0],0.62,'207.5 nm - 0.467',rotation=90,color=(0,0,1),fontsize=8)
#plt.text(ACh_B1.iloc[48,0],0.64,'220.5 nm - 0.880',rotation=90,color=(0,0,.7),fontsize=8)


ax.set_title("Absorbancia - Chiapas - B1",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right',)

ACh_B1_mean=(272.5+274+273.5)/3
print(ACh_B1_mean)

#Banda2  300 - 350
ACh_B2=ACh[(ACh['nm'] > 250) & (ACh['nm'] < 350)]
ACh_B2 = ACh_B2.reset_index()
ACh_B2.drop('index',axis=1,inplace=True)
print(ACh_B2)
#ProfileReport(ACh_B2)



#Banda2
#print(ACh_B2[ACh_B2.iloc[:,1]==0.238])
#print(ACh_B2[ACh_B2.iloc[:,2]==0.363])
#print(ACh_B2[ACh_B2.iloc[:,3]==0.648])

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(ACh_B2.iloc[:,0],ACh_B2.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(ACh_B2.iloc[:,0],ACh_B2.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(ACh_B2.iloc[:,0],ACh_B2.iloc[:,3],color=(0,0,.7),label='A50')



#plt.axvline(x=ACh_B2.iloc[11,0], color=(0.5,0.5,1), linestyle='--')
#plt.axvline(x=ACh_B2.iloc[16,0], color=(0,0,1), linestyle='--')
#plt.axvline(x=ACh_B2.iloc[12,0], color=(0,0,0.7), linestyle='--')

#plt.text(ACh_B2.iloc[10,0],0.4,'318 nm - 0.238',rotation=90,color=(0.5,0.5,1),fontsize=8)
#plt.text(ACh_B2.iloc[17,0],0.42,'320.5 nm - 0.363',rotation=90,color=(0,0,1),fontsize=8)
#plt.text(ACh_B2.iloc[13,0],0.44,'318.5 nm - 0.648',rotation=90,color=(0,0,.7),fontsize=8)


ax.set_title("Absorbancia - Chiapas - B2",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right')

ACh_B2_mean=(318+320.5+318.5)/3
print(ACh_B2_mean)

#---------------------------------------------------chiapas MG-----------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
AChMG05=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AChMG05.txt',engine='python',sep='\t',skiprows=8)
AChMG05.iloc[:,1]=pd.to_numeric(AChMG05['A'],errors='coerce')
AChMG05=np.array(AChMG05)

AChMG20=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AChMG20.txt',engine='python',sep='\t',skiprows=8)
AChMG20.iloc[:,1]=pd.to_numeric(AChMG20['A'],errors='coerce')
AChMG20=np.array(AChMG20)

AChMG50=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AChMG50.txt',engine='python',sep='\t',skiprows=8)
AChMG50.iloc[:,1]=pd.to_numeric(AChMG50['A'],errors='coerce')
AChMG50=np.array(AChMG50)
#---------------------------------------------------------------------------------------------------------------------
TChMG05=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TChMG05.txt',engine='python',sep='\t',skiprows=8)
TChMG05.iloc[:,1]=pd.to_numeric(TChMG05['%T'],errors='coerce')
TChMG05=np.array(TChMG05)

TChMG20=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TChMG20.txt',engine='python',sep='\t',skiprows=8)
TChMG20.iloc[:,1]=pd.to_numeric(TChMG20['%T'],errors='coerce')
TChMG20=np.array(TChMG20)

TChMG50=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TChMG50.txt',engine='python',sep='\t',skiprows=8)
TChMG50.iloc[:,1]=pd.to_numeric(TChMG50['%T'],errors='coerce')
TChMG50=np.array(TChMG50)
#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS
fig=plt.figure(figsize=(10,10))
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AChMG05[:,0],AChMG05[:,1],color=(0.5,0.5,1),label='AChMG05')
ax1.plot(AChMG20[:,0],AChMG20[:,1],color=(0,0,1),label='AChMG20')
ax1.plot(AChMG50[:,0],AChMG50[:,1],color=(0,0,.7),label='AChMG50')

ax1.text(AChMG05[8,0], AChMG05[8,1],'204 nm', fontsize=8)
ax1.text(AChMG20[15,0], AChMG20[15,1],'207.5 nm', fontsize=8)
ax1.text(AChMG50[41,0], AChMG50[41,1],'220.5 nm', fontsize=8)

ax1.set_title("Absorbancia - Chiapas",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------
ax2.plot(TChMG05[:,0],TChMG05[:,1],color=(1,0.5,0.5),label='TChMG05')
ax2.plot(TChMG20[:,0],TChMG20[:,1],color=(1,0,0),label='TChMG20')
ax2.plot(TChMG50[:,0],TChMG50[:,1],color=(0.7,0,0),label='TChMG50')
ax2.set_title("Transmitancia - Chiapas",fontsize=20)
ax2.set_xlabel('Longitud de Onda (nm)')
ax2.set_ylabel('Transmitancia (%)')
ax2.legend(loc='upper left')

fig.tight_layout()
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#CLEANING
AChMG=pd.DataFrame({'nm':AChMG05[:,0],'A05':AChMG05[:,1],'A20':AChMG20[:,1],'A50':AChMG50[:,1]})
AChMG.fillna(0,inplace=True)

TChMG=pd.DataFrame({'nm':TChMG05[:,0],'T05':TChMG05[:,1],'T20':TChMG20[:,1],'T50':TChMG50[:,1]})
TChMG.fillna(0,inplace=True)
#-------------------------------------------------------------------------------------------------------
#ProfileReport(AChMG)
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#-------------------MAXIMOS-------------------------------------------
print('\nMÁXIMOS\n',AChMG[AChMG.iloc[:,1]==1.449])
print(AChMG[AChMG.iloc[:,2]==1.528])
print(AChMG[AChMG.iloc[:,3]==1.555])
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#Banda1  250 - 300
AChMG_B1=AChMG[(AChMG['nm'] > 250) & (AChMG['nm'] < 300)]
AChMG_B1 = AChMG_B1.reset_index()
AChMG_B1.drop('index',axis=1,inplace=True)
#ProfileReport(AChMG_B1)

print('\nBANDA 1\n',AChMG_B1[AChMG_B1.iloc[:,1]==0.327])
print(AChMG_B1[AChMG_B1.iloc[:,2]==0.467])
print(AChMG_B1[AChMG_B1.iloc[:,3]==0.88])

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(AChMG_B1.iloc[:,0],AChMG_B1.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(AChMG_B1.iloc[:,0],AChMG_B1.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(AChMG_B1.iloc[:,0],AChMG_B1.iloc[:,3],color=(0,0,.7),label='A50')

plt.axvline(x=AChMG_B1.iloc[43,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AChMG_B1.iloc[46,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AChMG_B1.iloc[47,0], color=(0,0,0.7), linestyle='--')

plt.text(AChMG_B1.iloc[41,0],0.6,'272 nm - 0.327',rotation=90,color=(0.5,0.5,1),fontsize=8)
plt.text(AChMG_B1.iloc[44,0],0.62,'207.5 nm - 0.467',rotation=90,color=(0,0,1),fontsize=8)
plt.text(AChMG_B1.iloc[48,0],0.64,'220.5 nm - 0.880',rotation=90,color=(0,0,.7),fontsize=8)

ax.set_title("Absorbancia - Chiapas - B1",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#Banda2  300 - 350
AChMG_B2=AChMG[(AChMG['nm'] > 312) & (AChMG['nm'] < 350)]
AChMG_B2 = AChMG_B2.reset_index()
AChMG_B2.drop('index',axis=1,inplace=True)
#ProfileReport(AChMG_B2)

print('\nBanda 2\n',AChMG_B2[AChMG_B2.iloc[:,1]==0.238])
print(AChMG_B2[AChMG_B2.iloc[:,2]==0.363])
print(AChMG_B2[AChMG_B2.iloc[:,3]==0.648])

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(AChMG_B2.iloc[:,0],AChMG_B2.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(AChMG_B2.iloc[:,0],AChMG_B2.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(AChMG_B2.iloc[:,0],AChMG_B2.iloc[:,3],color=(0,0,.7),label='A50')

plt.axvline(x=AChMG_B2.iloc[11,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AChMG_B2.iloc[16,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AChMG_B2.iloc[12,0], color=(0,0,0.7), linestyle='--')

plt.text(AChMG_B2.iloc[10,0],0.4,'318 nm - 0.238',rotation=90,color=(0.5,0.5,1),fontsize=8)
plt.text(AChMG_B2.iloc[17,0],0.42,'320.5 nm - 0.363',rotation=90,color=(0,0,1),fontsize=8)
plt.text(AChMG_B2.iloc[13,0],0.44,'318.5 nm - 0.648',rotation=90,color=(0,0,.7),fontsize=8)


ax.set_title("Absorbancia - Chiapas - B2",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right')
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS CON BANDAS
fig=plt.figure(figsize=(20,10))
ax1 = fig.add_subplot(1, 1, 1)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AChMG05[:,0],AChMG05[:,1],color=(0.5,0.5,1),label='AChMG05')
ax1.plot(AChMG20[:,0],AChMG20[:,1],color=(0,0,1),label='AChMG20')
ax1.plot(AChMG50[:,0],AChMG50[:,1],color=(0,0,.7),label='AChMG50')

ax1.axvline(x=AChMG_B1.iloc[43,0], color=(0.5,0.5,1), linestyle='--')
ax1.axvline(x=AChMG_B1.iloc[46,0], color=(0,0,1), linestyle='--')
ax1.axvline(x=AChMG_B1.iloc[47,0], color=(0,0,0.7), linestyle='--')

ax1.axvline(x=AChMG_B2.iloc[11,0], color=(0.5,0.5,1), linestyle='--')
ax1.axvline(x=AChMG_B2.iloc[16,0], color=(0,0,1), linestyle='--')
ax1.axvline(x=AChMG_B2.iloc[12,0], color=(0,0,0.7), linestyle='--')

ax1.text(268,0,'B1',color='k',fontsize=10)
ax1.text(314,0,'B2',color='k',fontsize=10)

ax1.set_title("Absorbancia - Chiapas",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------

import seaborn as sns

sns.boxplot(x='A50', y='nm', data=AChMG)
#sns.boxplot(x='A20', y='nm', data=AChMG)
#sns.boxplot(x='A05', y='nm', data=AChMG)
plt.xlabel('nm')
plt.ylabel('A05')

plt.title('Blox plot de la Absorcion de A05')
plt.show()

sns.pairplot(AChMG)
plt.show()

sns.pairplot(AChMG, hue='nm', vars=['A05', 'A20','A50'])
plt.show()

AChMG_B1.head()

AChMG_B1.describe().T

from re import A
import pandas as pd
import numpy as np

# Assuming your DataFrame is called AChMG_B1
columns_to_check = ['A05','A20', 'A50']  # Or ['column1', 'column2', 'column3']
top_n = 3

if not all(col in AChMG_B1.columns for col in columns_to_check) and not all(isinstance(col, int) for col in columns_to_check):
    raise ValueError("Invalid column names or indices provided.")

cols_to_max = AChMG_B1.loc[:, columns_to_check]
max_values = cols_to_max.max()

mask = np.ones(len(AChMG_B1), dtype=bool)
for col in columns_to_check:
    mask &= (AChMG_B1[col] == max_values[col]).to_numpy()

selected_rows = AChMG_B1[mask]
print(selected_rows)
if len(selected_rows) > top_n:
    selected_rows = selected_rows.iloc[:top_n]

AChMG_B1_max = selected_rows.values
print(AChMG_B1_max)
AChMG_B1_mean = np.mean(AChMG_B1_max[:,0])
print(AChMG_B1_mean)

print(AChMG_B2.max())

#------------------hay que volver a cargar los datos de oaxaca de la memoria--------------------------------Oaxaca-----------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
AOxMM05=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AOxMM05.txt',engine='python',sep='\t',skiprows=8)
AOxMM05.iloc[:,1]=pd.to_numeric(AOxMM05.iloc[:,1],errors='coerce')
AOxMM05=np.array(AOxMM05)

AOxMM20=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AOxMM20.txt',engine='python',sep='\t',skiprows=8)
AOxMM20.iloc[:,1]=pd.to_numeric(AOxMM20.iloc[:,1],errors='coerce')
AOxMM20=np.array(AOxMM20)

AOxMM50=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AOxMM50.txt',engine='python',sep='\t',skiprows=8)
AOxMM50.iloc[:,1]=pd.to_numeric(AOxMM50.iloc[:,1],errors='coerce')
AOxMM50=np.array(AOxMM50)
#---------------------------------------------------------------------------------------------------------------------
TOxMM05=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TOxMM05.txt',engine='python',sep='\t',skiprows=8)
TOxMM05.iloc[:,1]=pd.to_numeric(TOxMM05.iloc[:,1],errors='coerce')
TOxMM05=np.array(TOxMM05)

TOxMM20=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TOxMM20.txt',engine='python',sep='\t',skiprows=8)
TOxMM20.iloc[:,1]=pd.to_numeric(TOxMM20.iloc[:,1],errors='coerce')
TOxMM20=np.array(TOxMM20)

TOxMM50=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TOxMM50.txt',engine='python',sep='\t',skiprows=8)
TOxMM50.iloc[:,1]=pd.to_numeric(TOxMM50.iloc[:,1],errors='coerce')
TOxMM50=np.array(TOxMM50)

#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS
fig=plt.figure(figsize=(10,10))
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AOxMM05[:,0],AOxMM05[:,1],color=(0.5,0.5,1),label='AOxMM05')
ax1.plot(AOxMM20[:,0],AOxMM20[:,1],color=(0,0,1),label='AOxMM20')
ax1.plot(AOxMM50[:,0],AOxMM50[:,1],color=(0,0,.7),label='AOxMM50')


#ax1.axvline(AChMG_B1_mean, color=(0,0.9,1), linestyle='--',label='AChMG_B1')
#ax1.axvline(AChMG_B2_mean, color=(0,0.9,1), linestyle='--',label='AChMG_B2')


ax1.set_title("Absorbancia - Oaxaca",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------
ax2.plot(TOxMM05[:,0],TOxMM05[:,1],color=(1,0.5,0.5),label='TOxMM05')
ax2.plot(TOxMM20[:,0],TOxMM20[:,1],color=(1,0,0),label='TOxMM20')
ax2.plot(TOxMM50[:,0],TOxMM50[:,1],color=(0.7,0,0),label='TOxMM50')
ax2.set_title("Transmitancia - Oaxaca",fontsize=20)
ax2.set_xlabel('Longitud de Onda (nm)')
ax2.set_ylabel('Transmitancia (%)')
ax2.legend(loc='upper left')

fig.tight_layout()

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#CLEANING
AOxMM=pd.DataFrame({'nm':AOxMM05[:,0],'A05':AOxMM05[:,1],'A20':AOxMM20[:,1],'A50':AOxMM50[:,1]})
AOxMM.fillna(0,inplace=True)

TOxMM=pd.DataFrame({'nm':TOxMM05[:,0],'T05':TOxMM05[:,1],'T20':TOxMM20[:,1],'T50':TOxMM50[:,1]})
TOxMM.fillna(0,inplace=True)

#-------------------------------------------------------------------------------------------------------
ProfileReport(AOxMM)

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#-------------------MAXIMOS-------------------------------------------

print(AOxMM['A05'].describe().loc[['min','max']])
print(AOxMM['A20'].describe().loc[['min','max']])
print(AOxMM['A50'].describe().loc[['min','max']])

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#Banda1  250 - 300
AOxMM_B1=AOxMM[(AOxMM['nm'] > 250) & (AOxMM['nm'] < 300)]
AOxMM_B1 = AOxMM_B1.reset_index()
AOxMM_B1.drop('index',axis=1,inplace=True)
#ProfileReport(AOxMM_B1)

print('\nBANDA 1\n',AOxMM_B1[AOxMM_B1.iloc[:,1]==0.327])
print(OxMM_B1[OxMM_B1.iloc[:,2]==0.467])
print(AOxMM_B1[AOxMM_B1.iloc[:,3]==0.88])

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(AOxMM_B1.iloc[:,0],AOxMM_B1.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(AOxMM_B1.iloc[:,0],AOxMM_B1.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(AOxMM_B1.iloc[:,0],AOxMM_B1.iloc[:,3],color=(0,0,.7),label='A50')

plt.axvline(x=AChMG_B1.iloc[43,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AChMG_B1.iloc[46,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AChMG_B1.iloc[47,0], color=(0,0,0.7), linestyle='--')

plt.text(AChMG_B1.iloc[41,0],0.6,'272 nm - 0.327',rotation=90,color=(0.5,0.5,1),fontsize=8)
plt.text(AChMG_B1.iloc[44,0],0.62,'207.5 nm - 0.467',rotation=90,color=(0,0,1),fontsize=8)
plt.text(AChMG_B1.iloc[48,0],0.64,'220.5 nm - 0.880',rotation=90,color=(0,0,.7),fontsize=8)

ax.set_title("Absorbancia - Oaxaca - B1",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#Banda2  300 - 350
AOxMM_B2=AOxMM[(AOxMM['nm'] > 312) & (AOxMM['nm'] < 350)]
AOxMM_B2 = AOxMM_B2.reset_index()
AOxMM_B2.drop('index',axis=1,inplace=True)
#ProfileReport(AOxMM_B2)

print('\nBanda 2\n',AOxMM_B2[AOxMM_B2.iloc[:,1]==0.238])
print(AOxMM_B2[AOxMM_B2.iloc[:,2]==0.363])
print(AOxMM_B2[AOxMM_B2.iloc[:,3]==0.648])

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(AOxMM_B2.iloc[:,0],AOxMM_B2.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(AOxMM_B2.iloc[:,0],AOxMM_B2.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(AOxMM_B2.iloc[:,0],AOxMM_B2.iloc[:,3],color=(0,0,.7),label='A50')

plt.axvline(x=AChMG_B2.iloc[11,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AChMG_B2.iloc[16,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AChMG_B2.iloc[12,0], color=(0,0,0.7), linestyle='--')

plt.text(AChMG_B2.iloc[10,0],0.4,'318 nm - 0.238',rotation=90,color=(0.5,0.5,1),fontsize=8)
plt.text(AChMG_B2.iloc[17,0],0.42,'320.5 nm - 0.363',rotation=90,color=(0,0,1),fontsize=8)
plt.text(AChMG_B2.iloc[13,0],0.44,'318.5 nm - 0.648',rotation=90,color=(0,0,.7),fontsize=8)


ax.set_title("Absorbancia - Oaxaca - B2",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right')
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS CON BANDAS
fig=plt.figure(figsize=(20,10))
ax1 = fig.add_subplot(1, 1, 1)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AOxMM05[:,0],AOxMM05[:,1],color=(0.5,0.5,1),label='AOxMM05')
ax1.plot(AOxMM20[:,0],AOxMM20[:,1],color=(0,0,1),label='AOxMM20')
ax1.plot(AOxMM50[:,0],AOxMM50[:,1],color=(0,0,.7),label='AOxMM50')

ax1.axvline(x=AChMG_B1.iloc[43,0], color=(0.5,0.5,1), linestyle='--')
ax1.axvline(x=AChMG_B1.iloc[46,0], color=(0,0,1), linestyle='--')
ax1.axvline(x=AChMG_B1.iloc[47,0], color=(0,0,0.7), linestyle='--')

ax1.axvline(x=AChMG_B2.iloc[11,0], color=(0.5,0.5,1), linestyle='--')
ax1.axvline(x=AChMG_B2.iloc[16,0], color=(0,0,1), linestyle='--')
ax1.axvline(x=AChMG_B2.iloc[12,0], color=(0,0,0.7), linestyle='--')

ax1.text(268,0,'B1',color='k',fontsize=10)
ax1.text(314,0,'B2',color='k',fontsize=10)

ax1.set_title("Absorbancia - Oaxaca",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)
#---------------------------------------------------------------------------------------------------------------------

#-------------------------------NO SON DEL MISMO TAMAÑO, BORRE LOS NAN. HAY QUE VOLVER A CARGAR LSO DATOS--------------------------------------------------------------------------------------

#---------------------------------------------------Mixteca Oaxaqueña-----------------------------------------------------------
#-------------------------------------------------------------------------------------------------------------------------------
AMiMG05=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AMiMG05.txt',engine='python',sep='\t',skiprows=8)
AMiMG05.iloc[:,1]=pd.to_numeric(AMiMG05['A'],errors='coerce')
AMiMG05=np.array(AMiMG05)

AMiMG20=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AMiMG20.txt',engine='python',sep='\t',skiprows=8)
AMiMG20.iloc[:,1]=pd.to_numeric(AMiMG20['A'],errors='coerce')
AMiMG20=np.array(AMiMG20)

AMiMG50=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /AMiMG50.txt',engine='python',sep='\t',skiprows=8)
AMiMG50.iloc[:,1]=pd.to_numeric(AMiMG50['A'],errors='coerce')
AMiMG50=np.array(AMiMG50)
#---------------------------------------------------------------------------------------------------------------------
TMiMG05=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TMiMG05.txt',engine='python',sep='\t',skiprows=8)
TMiMG05.iloc[:,1]=pd.to_numeric(TMiMG05['%T'],errors='coerce')
TMiMG05=np.array(TMiMG05)

TMiMG20=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TMiMG20.txt',engine='python',sep='\t',skiprows=8)
TMiMG20.iloc[:,1]=pd.to_numeric(TMiMG20['%T'],errors='coerce')
TMiMG20=np.array(TMiMG20)

TMiMG50=pd.read_csv('/content/drive/MyDrive/CafeLab/Data /TMiMG50.txt',engine='python',sep='\t',skiprows=8)
TMiMG50.iloc[:,1]=pd.to_numeric(TMiMG50['%T'],errors='coerce')
TMiMG50=np.array(TMiMG50)
#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS
fig=plt.figure(figsize=(10,10))
ax1 = fig.add_subplot(2, 1, 1)
ax2 = fig.add_subplot(2, 1, 2)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AMiMG05[:,0],AMiMG05[:,1],color=(0.5,0.5,1),label='AMiMG05')
ax1.plot(AMiMG20[:,0],AMiMG20[:,1],color=(0,0,1),label='AMiMG20')
ax1.plot(AMiMG50[:,0],AMiMG50[:,1],color=(0,0,.7),label='AMiMG50')

ax1.axvline(AChMG_B1_mean, color=(0,0.9,1), linestyle='--',label='AChMG_B1')
ax1.axvline(AChMG_B2_mean, color=(0,0.9,1), linestyle='--',label='AChMG_B2')

ax1.set_title("Absorbancia - Mixteca Oaxaqueña",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right')
#---------------------------------------------------------------------------------------------------------------------
ax2.plot(TMiMG05[:,0],TMiMG05[:,1],color=(1,0.5,0.5),label='TMiMG05')
ax2.plot(TMiMG20[:,0],TMiMG20[:,1],color=(1,0,0),label='TMiMG20')
ax2.plot(TMiMG50[:,0],TMiMG50[:,1],color=(0.7,0,0),label='TMiMG50')
ax2.set_title("Transmitancia - Mixteca Oaxaqueña",fontsize=20)
ax2.set_xlabel('Longitud de Onda (nm)')
ax2.set_ylabel('Transmitancia (%)')
ax2.legend(loc='upper left')

fig.tight_layout()

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#CLEANING
AMiMG=pd.DataFrame({'nm':AMiMG05[:,0],'A05':AMiMG05[:,1],'A20':AMiMG20[:,1],'A50':AMiMG50[:,1]})
AMiMG.fillna(0,inplace=True)

TMiMG=pd.DataFrame({'nm':TMiMG05[:,0],'T05':TMiMG05[:,1],'T20':TMiMG20[:,1],'T50':TMiMG50[:,1]})
TMiMG.fillna(0,inplace=True)
#-------------------------------------------------------------------------------------------------------
#ProfileReport(AMiMG)

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#-------------------MAXIMOS-------------------------------------------

print(AMiMG['A05'].describe().loc[['min','max']])
print(AMiMG['A20'].describe().loc[['min','max']])
print(AMiMG['A50'].describe().loc[['min','max']])

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#Banda1  250 - 300
AMiMG_B1=AMiMG[(AMiMG['nm'] > 250) & (AMiMG['nm'] < 300)]
AMiMG_B1 = AMiMG_B1.reset_index()
AMiMG_B1.drop('index',axis=1,inplace=True)
#ProfileReport(AMiMG_B1)

print('\nBANDA 1\n',AMiMG_B1[AMiMG_B1.iloc[:,1]==0.287])
print(AMiMG_B1[AMiMG_B1.iloc[:,2]==0.55])
print(AMiMG_B1[AMiMG_B1.iloc[:,3]==0.694])

AMiMG_B1_mean=(278+278.5+277.5)/3
print(AMiMG_B1_mean)

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(AMiMG_B1.iloc[:,0],AMiMG_B1.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(AMiMG_B1.iloc[:,0],AMiMG_B1.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(AMiMG_B1.iloc[:,0],AMiMG_B1.iloc[:,3],color=(0,0,.7),label='A50')

plt.axvline(x=AMiMG_B1.iloc[55,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AMiMG_B1.iloc[56,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AMiMG_B1.iloc[54,0], color=(0,0,0.7), linestyle='--')

plt.text(AMiMG_B1.iloc[57,0],0.6,'278 nm - 0.287',rotation=90,color=(0.5,0.5,1),fontsize=8)
plt.text(AMiMG_B1.iloc[59,0],0.62,'278.5 nm - 0.550',rotation=90,color=(0,0,1),fontsize=8)
plt.text(AMiMG_B1.iloc[52,0],0.64,'277.5 nm - 0.694',rotation=90,color=(0,0,.7),fontsize=8)

ax.set_title("Absorbancia - Mixteca Oaxaqueña - B1",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right',)

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#Banda2  300 - 350
AMiMG_B2=AMiMG[(AMiMG['nm'] > 312) & (AMiMG['nm'] < 350)]
AMiMG_B2 = AMiMG_B2.reset_index()
AMiMG_B2.drop('index',axis=1,inplace=True)
ProfileReport(AMiMG_B2)

print('\nBanda 2\n',AMiMG_B2[AMiMG_B2.iloc[:,1]==0.246])
print(AMiMG_B2[AMiMG_B2.iloc[:,2]==0.474])
print(AMiMG_B2[AMiMG_B2.iloc[:,3]==0.594])

AMiMG_B2_mean=(319.5+321.5+320.5)/3
print(AMiMG_B2_mean)

#GRAFICAMOS
plt.figure(figsize=(10,10))
ax=plt.subplot(1,1,1)
#---------------------------------------------------------------------------------------------------------------------
ax.plot(AMiMG_B2.iloc[:,0],AMiMG_B2.iloc[:,1],color=(0.5,0.5,1),label='A05')
ax.plot(AMiMG_B2.iloc[:,0],AMiMG_B2.iloc[:,2],color=(0,0,1),label='A20')
ax.plot(AMiMG_B2.iloc[:,0],AMiMG_B2.iloc[:,3],color=(0,0,.7),label='A50')

plt.axvline(x=AMiMG_B2.iloc[14,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AMiMG_B2.iloc[18,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AMiMG_B2.iloc[15,0], color=(0,0,0.7), linestyle='--')

plt.text(AMiMG_B2.iloc[12,0],0.4,'319.5 nm - 0.246',rotation=90,color=(0.5,0.5,1),fontsize=8)
plt.text(AMiMG_B2.iloc[19,0],0.42,'321.5 nm - 0.474',rotation=90,color=(0,0,1),fontsize=8)
plt.text(AMiMG_B2.iloc[16,0],0.44,'320 nm - 0.594',rotation=90,color=(0,0,.7),fontsize=8)


ax.set_title("Absorbancia - Mixteca Oaxaqueña - B2",fontsize=20)
ax.set_xlabel('Longitud de Onda (nm)')
ax.set_ylabel('Absorbancia')
ax.legend(loc='upper right')

#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------
#GRAFICAMOS CON BANDAS
fig=plt.figure(figsize=(20,10))
ax1 = fig.add_subplot(1, 1, 1)
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AMiMG05[:,0],AMiMG05[:,1],color=(0.5,0.5,1),label='AMiMG05')
ax1.plot(AMiMG20[:,0],AMiMG20[:,1],color=(0,0,1),label='AMiMG20')
ax1.plot(AMiMG50[:,0],AMiMG50[:,1],color=(0,0,.7),label='AMiMG50')

plt.axvline(x=AMiMG_B1.iloc[55,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AMiMG_B1.iloc[56,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AMiMG_B1.iloc[54,0], color=(0,0,0.7), linestyle='--')

plt.axvline(x=AMiMG_B2.iloc[14,0], color=(0.5,0.5,1), linestyle='--')
plt.axvline(x=AMiMG_B2.iloc[18,0], color=(0,0,1), linestyle='--')
plt.axvline(x=AMiMG_B2.iloc[15,0], color=(0,0,0.7), linestyle='--')

ax1.text(268,0,'B1',color='k',fontsize=10)
ax1.text(314,0,'B2',color='k',fontsize=10)


ax1.axvline(AChMG_B1_mean, color=(0,0.9,1), linestyle='--',label='AChMG_B1')
ax1.axvline(AChMG_B2_mean, color=(0,0.9,1), linestyle='--',label='AChMG_B2')


ax1.set_title("Absorbancia - Mixteca Oaxaqueña",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)


#---------------------------------------------------------------------------------------------------------------------

#GRAFICAMOS CHIAPAS - OAXACA - MIXTECA
fig,axes = plt.subplots(3, 1, figsize=(20,40),layout='constrained', facecolor='grey')

ax1=axes[0]
ax2=axes[1]
ax3=axes[2]
#---------------------------------------------------------------------------------------------------------------------
ax1.plot(AChMG05[:,0],AChMG05[:,1],color=(0.5,0.5,1),linestyle=':',label='AChMG05')
ax1.plot(AOxMM05[:,0],AOxMM05[:,1],color=(0.5,0.5,1),linestyle='-.',label='AOxMM05')
ax1.plot(AMiMG05[:,0],AMiMG05[:,1],color=(0.5,0.5,1),label='AMiMG05')
ax1.text(268,0,'B1',color='k',fontsize=10)
ax1.text(314,0,'B2',color='k',fontsize=10)
ax1.axvline(AChMG_B1_mean, color=(0,0.9,1),label=('AChMG_B1',round(AChMG_B1_mean,1)))
ax1.axvline(AMiMG_B1_mean, color=(0,0.9,0.5),label=('AMiMG_B1',AMiMG_B1_mean))
ax1.axvline(AChMG_B2_mean, color=(0,0.9,1),label=('AChMG_B2',AChMG_B2_mean))
ax1.axvline(AMiMG_B2_mean, color=(0,0.9,0.5),label=('AMiMG_B2',AMiMG_B2_mean))
ax1.set_title("Absorbancia (05) Chiapas - Oaxaca - Mixteca Oaxaqueña",fontsize=20)
ax1.set_xlabel('Longitud de Onda (nm)')
ax1.set_ylabel('Absorbancia')
ax1.legend(loc='upper right',)

ax2.plot(AChMG20[:,0],AChMG20[:,1],color=(0,0,1),linestyle=':',label='AChMG20')
ax2.plot(AOxMM20[:,0],AOxMM20[:,1],color=(0,0,1),linestyle='-.',label='AOxMM20')
ax2.plot(AMiMG20[:,0],AMiMG20[:,1],color=(0,0,1),label='AMiMG20')
ax2.text(268,0,'B1',color='k',fontsize=10)
ax2.text(314,0,'B2',color='k',fontsize=10)
ax2.axvline(AChMG_B1_mean, color=(0,0.9,1),label=('AChMG_B1',round(AChMG_B1_mean,1)))
ax2.axvline(AMiMG_B1_mean, color=(0,0.9,0.5),label=('AMiMG_B1',AMiMG_B1_mean))
ax2.axvline(AChMG_B2_mean, color=(0,0.9,1),label=('AChMG_B2',AChMG_B2_mean))
ax2.axvline(AMiMG_B2_mean, color=(0,0.9,0.5),label=('AMiMG_B2',AMiMG_B2_mean))
ax2.set_title("Absorbancia (20) Chiapas - Oaxaca - Mixteca Oaxaqueña",fontsize=20)
ax2.set_xlabel('Longitud de Onda (nm)')
ax2.set_ylabel('Absorbancia')
ax2.legend(loc='upper right',)

ax3.plot(AChMG50[:,0],AChMG50[:,1],color=(0,0,1),linestyle=':',label='AChMG50')
ax3.plot(AOxMM50[:,0],AOxMM50[:,1],color=(0,0,1),linestyle='-.',label='AOxMM50')
ax3.plot(AMiMG50[:,0],AMiMG50[:,1],color=(0,0,1),label='AMiMG50')
ax3.text(268,0,'B1',color='k',fontsize=10)
ax3.text(314,0,'B2',color='k',fontsize=10)
ax3.axvline(AChMG_B1_mean, color=(0,0.9,1),label=('AChMG_B1',round(AChMG_B1_mean,1)))
ax3.axvline(AMiMG_B1_mean, color=(0,0.9,0.5),label=('AMiMG_B1',AMiMG_B1_mean))
ax3.axvline(AChMG_B2_mean, color=(0,0.9,1),label=('AChMG_B2',AChMG_B2_mean))
ax3.axvline(AMiMG_B2_mean, color=(0,0.9,0.5),label=('AMiMG_B2',AMiMG_B2_mean))
ax3.set_title("Absorbancia (50) Chiapas - Oaxaca - Mixteca Oaxaqueña",fontsize=20)
ax3.set_xlabel('Longitud de Onda (nm)')
ax3.set_ylabel('Absorbancia')
ax3.legend(loc='upper right',)

axes[0].set_ylim(0,1.8)
axes[1].set_ylim(0,1.8)
axes[2].set_ylim(0,1.8)
fig.tight_layout()

#---------------------------------------------------Guerrero-----------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------

#---------------------------------------------------chiapas-----------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------

#---------------------------------------------------chiapas MN-----------------------------------------------------------
#---------------------------------------------------------------------------------------------------------------------